<?php

//This config file is autogenerated.
//You shouldn't override it and expect good things.

namespace malamute;

defined('ABSPATH') or exit;

global $codemirror_themes;

$codemirror_themes = array(
	'dracula' => array (
		'name' => 'dracula',
		'file' => 'dracula.css'
	),
	'paraiso-light' => array (
		'name' => 'paraiso-light',
		'file' => 'paraiso-light.css'
	),
	'yeti' => array (
		'name' => 'yeti',
		'file' => 'yeti.css'
	),
	'liquibyte' => array (
		'name' => 'liquibyte',
		'file' => 'liquibyte.css'
	),
	'panda-syntax' => array (
		'name' => 'panda-syntax',
		'file' => 'panda-syntax.css'
	),
	'tomorrow-night-bright' => array (
		'name' => 'tomorrow-night-bright',
		'file' => 'tomorrow-night-bright.css'
	),
	'elegant' => array (
		'name' => 'elegant',
		'file' => 'elegant.css'
	),
	'paraiso-dark' => array (
		'name' => 'paraiso-dark',
		'file' => 'paraiso-dark.css'
	),
	'twilight' => array (
		'name' => 'twilight',
		'file' => 'twilight.css'
	),
	'ambiance' => array (
		'name' => 'ambiance',
		'file' => 'ambiance.css'
	),
	'cobalt' => array (
		'name' => 'cobalt',
		'file' => 'cobalt.css'
	),
	'monokai' => array (
		'name' => 'monokai',
		'file' => 'monokai.css'
	),
	'ambiance-mobile' => array (
		'name' => 'ambiance-mobile',
		'file' => 'ambiance-mobile.css'
	),
	'tomorrow-night-eighties' => array (
		'name' => 'tomorrow-night-eighties',
		'file' => 'tomorrow-night-eighties.css'
	),
	'material' => array (
		'name' => 'material',
		'file' => 'material.css'
	),
	'neat' => array (
		'name' => 'neat',
		'file' => 'neat.css'
	),
	'night' => array (
		'name' => 'night',
		'file' => 'night.css'
	),
	'eclipse' => array (
		'name' => 'eclipse',
		'file' => 'eclipse.css'
	),
	'midnight' => array (
		'name' => 'midnight',
		'file' => 'midnight.css'
	),
	'the-matrix' => array (
		'name' => 'the-matrix',
		'file' => 'the-matrix.css'
	),
	'3024-day' => array (
		'name' => '3024-day',
		'file' => '3024-day.css'
	),
	'railscasts' => array (
		'name' => 'railscasts',
		'file' => 'railscasts.css'
	),
	'vibrant-ink' => array (
		'name' => 'vibrant-ink',
		'file' => 'vibrant-ink.css'
	),
	'pastel-on-dark' => array (
		'name' => 'pastel-on-dark',
		'file' => 'pastel-on-dark.css'
	),
	'neo' => array (
		'name' => 'neo',
		'file' => 'neo.css'
	),
	'isotope' => array (
		'name' => 'isotope',
		'file' => 'isotope.css'
	),
	'base16-dark' => array (
		'name' => 'base16-dark',
		'file' => 'base16-dark.css'
	),
	'3024-night' => array (
		'name' => '3024-night',
		'file' => '3024-night.css'
	),
	'duotone-dark' => array (
		'name' => 'duotone-dark',
		'file' => 'duotone-dark.css'
	),
	'colorforth' => array (
		'name' => 'colorforth',
		'file' => 'colorforth.css'
	),
	'ttcn' => array (
		'name' => 'ttcn',
		'file' => 'ttcn.css'
	),
	'bespin' => array (
		'name' => 'bespin',
		'file' => 'bespin.css'
	),
	'hopscotch' => array (
		'name' => 'hopscotch',
		'file' => 'hopscotch.css'
	),
	'duotone-light' => array (
		'name' => 'duotone-light',
		'file' => 'duotone-light.css'
	),
	'erlang-dark' => array (
		'name' => 'erlang-dark',
		'file' => 'erlang-dark.css'
	),
	'rubyblue' => array (
		'name' => 'rubyblue',
		'file' => 'rubyblue.css'
	),
	'zenburn' => array (
		'name' => 'zenburn',
		'file' => 'zenburn.css'
	),
	'xq-dark' => array (
		'name' => 'xq-dark',
		'file' => 'xq-dark.css'
	),
	'solarized' => array (
		'name' => 'solarized',
		'file' => 'solarized.css'
	),
	'seti' => array (
		'name' => 'seti',
		'file' => 'seti.css'
	),
	'icecoder' => array (
		'name' => 'icecoder',
		'file' => 'icecoder.css'
	),
	'xq-light' => array (
		'name' => 'xq-light',
		'file' => 'xq-light.css'
	),
	'mdn-like' => array (
		'name' => 'mdn-like',
		'file' => 'mdn-like.css'
	),
	'blackboard' => array (
		'name' => 'blackboard',
		'file' => 'blackboard.css'
	),
	'mbo' => array (
		'name' => 'mbo',
		'file' => 'mbo.css'
	),
	'lesser-dark' => array (
		'name' => 'lesser-dark',
		'file' => 'lesser-dark.css'
	),
	'base16-light' => array (
		'name' => 'base16-light',
		'file' => 'base16-light.css'
	),
	'abcdef' => array (
		'name' => 'abcdef',
		'file' => 'abcdef.css'
	)
);
